### ISSUE TITLE
Tutorials - TextInput - Error

### ISSUE THREAD

**Issue by maavelar5** [libsdl-org/ghwikipp#21]
https://wiki.libsdl.org/Tutorials/TextInput returns an HTTP 400 error code.

![image](https://user-images.githubusercontent.com/10832665/113233164-3647eb80-9264-11eb-985a-c130c914955e.png)

**Comment by icculus** [comment]
If you need this content before I fix this:

https://web.archive.org/web/20210330154506/https://wiki.libsdl.org/Tutorials/TextInput

**Comment by kivan117** [comment]
https://wiki.libsdl.org/Tutorials/AudioStream

Same error observed. I did not open a new issue as it's possibly related.

**Comment by icculus** [comment]
Yeah, it's any wiki page with a '/' in it.

**Comment by jpgleeson** [comment]
This content is live at https://wiki.libsdl.org/Tutorials-TextInput
The markup file in the content repo is Tutorials-TextInput.mediawiki, so the cooker outputs it to the url above.

Fixing subdirectories so they work as an "operation" would be good to have regardless, but in this case I think the content file is just linking to the wrong location.

**Comment by icculus** [comment]
So we've had real subdirectory support for a while now, so we _could_ have `SDL3/Tutorials/TextInput` now, but we changed these specific things a long time ago to have a hyphen, so we're going to leave it alone instead of moving those pages again.

**Comment by icculus** [comment]
(This particular URL still reports `400 Bad Request` because ghwikipp only accepts subdirectories it can see on the filesystem, and if they aren't already there, it treats this as an unknown operation on the "Tutorials" wiki page. This is maybe confusing but also maybe correct. Web development is hard.)
