### ISSUE TITLE
Discoverable anchors on sections?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/ghwikipp#23]
Right now each section has an anchor, like this:

https://wiki.libsdl.org/SDL_OpenAudioDevice#code-examples

...but these aren't apparent in the displayed page. It'd be nice if when mousing over a section, a little link icon appeared that indicated you could link directly to this location.

**Comment by jpgleeson** [comment]
I'm thinking it's probably easiest to implement this in the pandoc-filter.lua file to add a hidden svg icon to every header2. I'm going to take a bash at this but I've never written a pandoc filter before so I will have to see how it goes.

Should each item also be a link that directs to self to allow for easy fetching of the url?

**Comment by icculus** [comment]
> Should each item also be a link that directs to self to allow for easy fetching of the url?

That's what I was thinking, yeah, but you've already made it further than I did.  :)

The link icons are live on wiki.libsdl.org if you want to see them in action. Feel free to make them linkable if you want to push another change!
