### ISSUE TITLE
503 After Authorising Github Email Access

### ISSUE THREAD

**Issue by Altazimuth** [libsdl-org/ghwikipp#24]
I authorised SDL's Wiki to have user:email scope but get a 503 on the wiki with the following error:
 > GitHub won't tell us your email address, which we need to make edits to the wiki. Check your settings on GitHub?

This is in spite of the following:
![image](https://user-images.githubusercontent.com/5298767/113487369-9ed6d880-94af-11eb-8ad1-e7714f01f2a2.png)

For reference my Github account has one primary email and three secondaries. I don't know if this may be a factor.

**Comment by icculus** [comment]
I changed the error to dump out some debug information; if you could paste that in here (or [email me](mailto:icculus@icculus.org) if you prefer), I can probably figure out what happened.

**Comment by Altazimuth** [comment]
Email sent. I'm posting part of the debug output that appears non-sensitive but also important.
```
    [location] => Bromley, London
    [email] => 
    [hireable] => 
    [bio] => Software engineer at Nightdive Studios. Doom enthusiast.
```
The email being blank is very suspect, though I suppose might be obvious given the initial error given.

**Comment by Altazimuth** [comment]
The current fix is to uncheck the following in the Github settings.
![image](https://user-images.githubusercontent.com/5298767/114442806-ddae1200-9bc4-11eb-8350-700996274f87.png)

**Comment by icculus** [comment]
This is fixed now, people can now keep their email addresses private and still edit the wiki.
