### ISSUE TITLE
Garbage text on SDL_Keycode wiki page

### ISSUE THREAD

**Issue by Clark-E** [libsdl-org/ghwikipp#27]
On the wiki page for [SDL_Keycode](https://wiki.libsdl.org/SDL_Keycode), this text is present:

![image](https://user-images.githubusercontent.com/35299276/114280602-0806a080-9a08-11eb-9104-55d74f30942f.png)

I assume this text was meant to be replaced/filled in via an automated script.

**Comment by icculus** [comment]
Transferred to the sdlwiki bug tracker and closing here.
