### ISSUE TITLE
Enumerations, structures, and functions all merged into one list

### ISSUE THREAD

**Issue by clarityflowers** [libsdl-org/ghwikipp#29]
Comparing https://wiki.libsdl.org/CategoryVideo via the wayback machine and the new version:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/12554076/114314842-3ee4c100-9ab1-11eb-8829-d858c9a2b73c.png">

**Comment by HolyBlackCat** [comment]
Any updates on this? http://wiki.libsdl.org/CategoryAPI , which is essentially the single most important page of the wiki, is still broken in this manner. :/

**Comment by chelmich** [comment]
It's worse than them being merged into one list, the links for structs and enums are just plain missing from category pages. I tried to see if it was something I could fix but I don't really know anything about PHP. Hope this gets fixed soon.

**Comment by ghost** [comment]
Well it is still happening, and it's a shame because it means users can't contribute to these pages easily.

**Comment by icculus** [comment]
This is resolved now, finally. The category lists are maintained automatically, so contributions to those pages would be fleshing out category documentation _above_ the lists on the page. Like, basic rundowns of a specific subsystem, how to get started using it, etc.
