### ISSUE TITLE
CategoryEvents broken

### ISSUE THREAD

**Issue by DanielGibson** [libsdl-org/ghwikipp#31]
For some reason https://wiki.libsdl.org/CategoryEvents doesn't exist, even though https://github.com/libsdl-org/sdlwiki/blob/main/CategoryEvents.mediawiki does

**Comment by icculus** [comment]
Generally this means pandoc failed to cook it. Checking.

**Comment by icculus** [comment]
This is fixed in https://github.com/libsdl-org/sdlwiki/commit/8901201cce7bc5656a1cf6dcc898f4adda53d76e

**Comment by DanielGibson** [comment]
thanks!
