### ISSUE TITLE
Bug in SDL Wiki documentation

### ISSUE THREAD

**Issue by chris-dent** [libsdl-org/ghwikipp#39]
In the Example seection of the SDL_RenderPresent page (https://wiki.libsdl.org/SDL_RenderPresent)
The example code is
<<Include(SDL_RenderClear, , , from="== Code Examples ==", to="== Remarks ==")>>

**Comment by icculus** [comment]
There's a bug on the sdlwiki repo for this: https://github.com/libsdl-org/sdlwiki/issues/233
