### ISSUE TITLE
Code examples not showing

### ISSUE THREAD

**Issue by alexclifton4** [libsdl-org/ghwikipp#42]
On a few of the pages about Mutexes such as this one: https://wiki.libsdl.org/SDL_UnlockMutex
The code example is not showing. Instead, the following text is shown:
Code Examples
<<Include(SDL_CreateMutex, , , from="## Begin Mutex Example", to="## End Mutex Example")>>

**Comment by icculus** [comment]
There's an sdlwiki bug for this: https://github.com/libsdl-org/sdlwiki/issues/233
