### ISSUE TITLE
Bug on the remarks section

### ISSUE THREAD

**Issue by TerensTare** [libsdl-org/ghwikipp#43]
I was browsing the SDL2 docs about [`SDL_RendererInfo`](https://wiki.libsdl.org/SDL_RendererInfo#remarks) and some parts of the `Remarks` were not rendering correctly (notice the `<<Include(...)>>` parts). Here's a screenshot displaying the incorrect behavior: 
![image](https://user-images.githubusercontent.com/37905314/132140874-ae301b5b-1c27-4ac2-91cc-fa0e61bc3334.png)

**Comment by beeryt** [comment]
Seen also on [`SDL_DisplayMode`](https://wiki.libsdl.org/SDL_DisplayMode).

**Comment by icculus** [comment]
So these are leftovers from SDL's old wiki and they've been getting cleaned out. Closing this because it's not a bug in ghwikipp.

I've made sure there's a bug in sdlwiki for it, though: https://github.com/libsdl-org/sdlwiki/issues/233
