### ISSUE TITLE
I think I find a bug with SDL Library

### ISSUE THREAD

**Issue by ArnaudNRoses** [libsdl-org/ghwikipp#44]
Hello !

When I use the function SDL_RenderSetLogicalSize() and the Sclale done by this function in X and Y are differents of 1.0f ( in float), the function SDL_SetWindowGrab(pWindow, SDL_TRUE) does not takes this effect, the mouse is not grabbed in the window. When ( in my same program ) the renderer have no set a logical size ( relative to screen format ), the function SDL_SetWindowGrab(pWindow, SDL_TRUE) works perfectly, the mouse is perfectly grabbed.

I try some things for take the mouse grabbed but I d'ont find solution.

 It is a bug from thiss functions ?

Thanks for any help...

Arnaud

**Comment by Dobby233Liu** [comment]
go to https://github.com/libsdl-org/SDL/issues
