### ISSUE TITLE
Search results might be broken.

### ISSUE THREAD

**Issue by blaisemccourtney** [libsdl-org/ghwikipp#55]
When putting in the search term "SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED", some results are gotten. When clicking on the "[SDL_EventType](https://wiki.libsdl.org/SDL_EventType)" search result, you are redirected to https://wiki.libsdl.org/SDL2/SDL_EventType . However, "SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED" does not occur on that page, only on the SDL3 version.

**Comment by icculus** [comment]
Okay, this fix is live on wiki.libsdl.org now!

https://wiki.libsdl.org/wiki/search?q=SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED
